name: "Build Feed"

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
  workflow_call:
  schedule:
      # Runs "at minute 1 past midnight" (see https://crontab.guru)
      - cron: '1 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get commit date
      run: |
        echo "COMMIT_DATE=$(git show -s --format=%ci HEAD)" >> "$GITHUB_ENV"

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.2

    - name: Process Feed
      run: |
        cd generator
        bun install
        bun .

    - name: If new, exit this job
      id: check_version
      run: |
       git status --porcelain
       if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "New feed generated, committing changes."
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No new feed generated, exiting job."
          fi

    - name: Commit to branch
      uses: EndBug/add-and-commit@v9
      if: steps.check_version.outputs.changed == 'true'
      with:
          message: '🚌 Update feed'
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit: --signoff
          default_author: github_actions
          pull: '--rebase --autostash'

    - name: Package new feed
      if: steps.check_version.outputs.changed == 'true'
      run: |
        cd fragment
        zip -r gtfs.zip .

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './fragment/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
